sudo: required
services:
  - docker

before_install:
  - docker build -t maunconsultancy/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run maunconsultancy/react-test npm test -- --coverage

after_success:
  - docker build -t maunconsultancy/multi-client ./client
  - docker build -t maunconsultancy/multi-nginx ./nginx
  - docker build -t maunconsultancy/multi-server ./server
  - docker build -t maunconsultancy/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push maunconsultancy/multi-client
  - docker push maunconsultancy/multi-nginx
  - docker push maunconsultancy/multi-server
  - docker push maunconsultancy/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-eu-west-2-196281924436
  bucket_path: MultiDockerdocker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY